# Generated by Django 5.0.4 on 2024-06-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_amount',
            new_name='current_bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
        migrations.AddField(
            model_name='bid',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
