# Generated by Django 5.0.4 on 2024-06-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_bid_amount_bid_current_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='end_bid',
            field=models.DateTimeField(null=True),
        ),
    ]
